// Code generated by MockGen. DO NOT EDIT.
// Source: plugin/iface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	cocov "github.com/cocov-ci/go-plugin-kit/cocov"
	gomock "github.com/golang/mock/gomock"
)

// Mockexecutor is a mock of executor interface.
type Mockexecutor struct {
	ctrl     *gomock.Controller
	recorder *MockexecutorMockRecorder
}

// MockexecutorMockRecorder is the mock recorder for Mockexecutor.
type MockexecutorMockRecorder struct {
	mock *Mockexecutor
}

// NewMockexecutor creates a new mock instance.
func NewMockexecutor(ctrl *gomock.Controller) *Mockexecutor {
	mock := &Mockexecutor{ctrl: ctrl}
	mock.recorder = &MockexecutorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockexecutor) EXPECT() *MockexecutorMockRecorder {
	return m.recorder
}

// Exec2 mocks base method.
func (m *Mockexecutor) Exec2(arg0 string, arg1 []string, arg2 *cocov.ExecOpts) ([]byte, []byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exec2", arg0, arg1, arg2)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].([]byte)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Exec2 indicates an expected call of Exec2.
func (mr *MockexecutorMockRecorder) Exec2(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exec2", reflect.TypeOf((*Mockexecutor)(nil).Exec2), arg0, arg1, arg2)
}
