#!/bin/bash

if ! which mockgen 1>&2 > /dev/null; then
  echo "Seems like gomock is not installed. Do you wish to proceed with the installation?[y/n]"
  read -r proceed
  if [ "$proceed" = "y" ]; then
    go install github.com/golang/mock/mockgen@v1.6.0
    go get -u github.com/golang/mock/mockgen/model
  else
    echo "Please refer to gomock for more details: https://github.com/golang/mock"
    exit 1
  fi
fi

rm -rfv mocks
mkdir -p common/mocks
# shellcheck disable=SC2164
cd common

mockgen -package=sdkmocks github.com/cocov-ci/go-plugin-kit/cocov Context > mocks/context.go